import test from 'node:test';
import assert from 'node:assert/strict';
import { pbkdf2 as pbkdf2Callback } from 'node:crypto';
import { promisify } from 'node:util';
import { createLegacyImportId, createLegacyUserData, sanitizeLegacyMember, verifyLegacyPassword } from './legacy-import-service.mjs';

const pbkdf2 = promisify(pbkdf2Callback);
const saltHex = '0123456789abcdef0123456789abcdef';
const password = 'legacy-password-for-test';
const passwordHash = (await pbkdf2(password, Buffer.from(saltHex, 'hex'), 120_000, 32, 'sha256')).toString('hex');

function legacyRecord(overrides = {}) {
    return {
        id: 'member_1730000000000_ab12cd',
        name: 'Candidate One',
        email: 'Candidate@example.test',
        exam: 'SI',
        passwordSalt: saltHex,
        passwordHash,
        userProgress: {
            Percentages: { level: 'Intermediate', bestScore: 8, attempts: 4, accuracy: 75 }
        },
        testHistory: [{
            id: 'att_1730000000000_ab123',
            exam: 'SI',
            subject: 'Arithmetic',
            topic: 'Percentages',
            difficulty: 'Beginner',
            score: 1,
            total: 1,
            correct: 1,
            incorrect: 0,
            unanswered: 0,
            percentage: 100,
            accuracy: 100,
            status: 'LEVEL PASSED',
            date: '2024-10-27',
            timeTaken: '00:30',
            questions: [{
                questionId: 'q1', question: 'What is 1 + 1?', options: ['2', '3'], userAnswer: '2',
                correctAnswer: '2', isCorrect: true, status: 'CORRECT', explanation: 'Add one.', shortcut: ''
            }],
            answerKey: [{ questionId: 'q1', correctAnswer: '2' }]
        }],
        seenQuestionCount: 40,
        testAttemptCounter: 4,
        plannerData: {
            examType: 'SI',
            generatedAt: null,
            summary: { testsAttempted: 4, averageAccuracy: 75 },
            topicMetrics: [{ subject: 'Arithmetic', topic: 'Percentages', accuracy: 75 }],
            schedule: [{
                id: 'manual-1', examType: 'SI', subject: 'Arithmetic', topic: 'Percentages',
                date: '2026-10-01', startTime: '09:00', endTime: '10:00', duration: 60,
                priority: 'MEDIUM', reason: 'Review', notes: 'Bring notebook', status: 'scheduled', autoGenerated: false
            }]
        },
        ...overrides
    };
}

test('legacy password verification matches PBKDF2-SHA256 browser hashes', async () => {
    assert.equal(await verifyLegacyPassword(password, saltHex, passwordHash), true);
    assert.equal(await verifyLegacyPassword('incorrect-password', saltHex, passwordHash), false);
});

test('legacy password verification rejects malformed salt and hash encodings', async () => {
    assert.equal(await verifyLegacyPassword(password, 'xyz', passwordHash), false);
    assert.equal(await verifyLegacyPassword(password, saltHex, 'ab'.repeat(31)), false);
});

test('legacy member sanitization normalizes email and fingerprints state without credentials', () => {
    const record = legacyRecord();
    const first = sanitizeLegacyMember(record);
    const second = sanitizeLegacyMember({ ...record, passwordSalt: 'fedcba9876543210fedcba9876543210', passwordHash: 'f'.repeat(64) });
    assert.equal(first.email, 'candidate@example.test');
    assert.equal(first.fingerprint, second.fingerprint);
    assert.equal(first.userProgress.Percentages.verified, false);
    assert.equal(first.testHistory[0].verified, false);
    assert.equal('passwordHash' in first, true);
});

test('legacy member sanitization rejects malformed and oversized records', () => {
    assert.throws(() => sanitizeLegacyMember(legacyRecord({ id: 'usr_client-selected-id' })), { code: 'INVALID_LEGACY_RECORD' });
    assert.throws(() => sanitizeLegacyMember(legacyRecord({ email: 'not-an-email' })), { code: 'INVALID_LEGACY_RECORD' });
    assert.throws(() => sanitizeLegacyMember(legacyRecord({ userProgress: { UnknownTopic: { level: 'Pro', bestScore: 10, attempts: 1, accuracy: 100 } } })), { code: 'INVALID_LEGACY_RECORD' });
    assert.throws(() => sanitizeLegacyMember(legacyRecord({ testHistory: Array(501).fill({}) })), { code: 'INVALID_LEGACY_RECORD' });
    assert.throws(() => sanitizeLegacyMember(legacyRecord({ plannerData: { examType: 'SI', generatedAt: null, summary: {}, topicMetrics: [], schedule: Array(1001).fill({}) } })), { code: 'INVALID_LEGACY_RECORD' });
});

test('legacy imports preserve planner reason and exam type while using a generated account ID', () => {
    const legacy = sanitizeLegacyMember(legacyRecord());
    const userId = createLegacyImportId();
    const data = createLegacyUserData(userId, legacy, '2026-09-30T00:00:00.000Z');
    assert.match(userId, /^usr_[a-f\d-]{36}$/i);
    assert.equal(data.userId, userId);
    assert.equal(data.userProgress.Percentages, undefined);
    assert.equal(data.legacyArchive.userProgress.Percentages.verified, false);
    assert.equal(data.legacyArchive.testHistory[0].legacy, true);
    assert.equal(data.plannerData.schedule[0].userId, userId);
    assert.equal(data.plannerData.schedule[0].reason, 'Review');
    assert.equal(data.plannerData.schedule[0].examType, 'SI');
});